apiVersion: v1
kind: Secret
metadata:
  name: jfrog-registry-secret
  namespace: vault-deployment
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0cmlhbGQ0bHliYi5qZnJvZy5pbyI6eyJ1c2VybmFtZSI6ImFzaGlzaG1ha2FzYXJlMjRAZ21haWwuY29tIiwicGFzc3dvcmQiOiJBc2hpc2hAMTIzIiwiYXV0aCI6IllYTm9hWE5vYldGcllYTmhjbVV5TkVCbmJXRnBiQzVqYjIwNlFYTm9hWE5vUURFeU13PT0ifX19
