<<<<<<< HEAD
apiVersion: v1
kind: Secret
metadata:
  name: jfrog-registry-secret
  namespace: vault-deployment
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJ0cmlhbDdlMmgxaS5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogImFzaGlzaG1ha2FzYXJlMjRAZ21haWwuY29tIiwKICAgICAgInBhc3N3b3JkIjogIkFzaGlzaEAxMjMiLAogICAgICAiYXV0aCI6ICJZWE5vYVhOb2JXRnJZWE5oY21VeU5FQm5iV0ZwYkM1amIyMDZRWE5vYVhOb1FERXlNdz09IgogICAgfQogIH0KfQo=
=======
apiVersion: v1
kind: Secret
metadata:
  name: jfrog-registry-secret
  namespace: vault-deployment
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0cmlhbHU0dGJieS5qZnJvZy5pbyI6eyJ1c2VybmFtZSI6ImFzaGlzaG1ha2FzYXJlMjRAZ21haWwuY29tIiwicGFzc3dvcmQiOiJBc2hpc2hAMTIzIiwiYXV0aCI6IllYTm9hWE5vYldGcllYTmhjbVV5TkVCbmJXRnBiQzVqYjIwNlFYTm9hWE5vUURFeU13PT0ifX19
>>>>>>> upstream/main
