apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault-deployment
data:
  vault.hcl: |
    # Storage backend using Raft for HA
    storage "raft" {
      path    = "/vault/data"
      node_id = "vault-0"  # Ensure unique node_id for each instance
    }

    # Listener configuration for Vault
    listener "tcp" {
      address         = "0.0.0.0:8200"
      tls_disable     = 0
      tls_cert_file   = "/vault/certs/tls.crt"
      tls_key_file    = "/vault/certs/tls.key"
    }

    # API address for external access
    api_addr = "https://vault.minikube.local"  # Use Ingress host

    # Cluster address for Raft communication
    cluster_addr = "https://vault.vault-deployment.svc.cluster.local:8201"

    # Enable the Vault UI
    ui = true

    # Disable memory lock to allow running as a non-root user
    disable_mlock = true

    # Seal configuration using Shamir Secret Sharing
    seal "shamir" {
      secret_shares    = 3
      secret_threshold = 2
    }

    telemetry {
      prometheus_retention_time = "24h"
    }