apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: vault-deployment                      # Ensure the correct namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"            # Ensures that the path is redirected to root
    nginx.ingress.kubernetes.io/ssl-redirect: "true"         # Enforces HTTP to HTTPS redirection
    nginx.ingress.kubernetes.io/secure-backends: "true"      # Secures communication between Ingress and Vault backend
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "vault-deployment/vault-ssl-cert"   
spec:
  ingressClassName: nginx                                # Explicitly define the Ingress class
  rules:
  - host: vault.minikube.local                                      # Replace with your actual domain if needed (ensure it resolves to Minikube's IP)
    http:
      paths:
      - path: /                                            # The root path for Vault
        pathType: Prefix
        backend:
          service:
            name: vault                                    # Correct service name
            port:
              number: 8200                                  # Vault service port (ensure it matches the service)
  tls:
  - hosts:
    - vault.minikube.local                                          # Replace with your actual domain if needed
    secretName: vault-ssl-cert                             # Reference to the secret containing your TLS certs