global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'slack-notifications'
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#monitoring-alerts'