groups:
- name: vault_alerts
  rules:
  - alert: VaultHighErrorRate
    expr: increase(vault_request_errors[5m]) > 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High error rate detected in Vault"
      description: "Vault has a high error rate of {{ $value }} errors in the last 5 minutes."